# Generated by Django 4.2.16 on 2025-10-31 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_psychologicalissue_sessionrequest_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='session',
        ),
        migrations.RemoveField(
            model_name='sessionrequest',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='sessionrequest',
            name='matched_therapists',
        ),
        migrations.RemoveField(
            model_name='sessionrequest',
            name='patient',
        ),
        migrations.AlterUniqueTogether(
            name='therapistspecialty',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='therapistspecialty',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='therapistspecialty',
            name='therapist',
        ),
        migrations.RemoveField(
            model_name='therapysession',
            name='request',
        ),
        migrations.RemoveField(
            model_name='therapysession',
            name='therapist',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CallSession',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='SessionRequest',
        ),
        migrations.DeleteModel(
            name='TherapistSpecialty',
        ),
        migrations.DeleteModel(
            name='TherapySession',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
