# Generated by Django 4.2.16 on 2025-10-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_remove_chatmessage_sender_remove_chatmessage_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologicalissue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='psychological_issues/'),
        ),
    ]
