# Generated by Django 4.2.16 on 2025-11-01 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0004_psychologicalissue_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان فرم')),
                ('title_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان فارسی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psychological_issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='authapp.psychologicalissue', verbose_name='مسئله روانشناختی')),
            ],
            options={
                'verbose_name': 'فرم',
                'verbose_name_plural': 'فرم\u200cها',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='authapp.form', verbose_name='فرم')),
                ('psychological_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='authapp.psychologicalissue', verbose_name='مسئله روانشناختی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پاسخ فرم',
                'verbose_name_plural': 'پاسخ\u200cهای فرم',
                'ordering': ['-created_at'],
                'unique_together': {('form', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='متن سوال')),
                ('text_fa', models.CharField(blank=True, max_length=500, null=True, verbose_name='متن فارسی سوال')),
                ('question_type', models.CharField(choices=[('yes_no', 'بله/خیر'), ('descriptive', 'توضیحات (متن طولانی)'), ('multiple_choice_4', 'چهار گزینه\u200cای'), ('short_text', 'متن کوتاه'), ('number', 'عدد')], default='descriptive', max_length=20, verbose_name='نوع سوال')),
                ('options', models.TextField(blank=True, help_text='برای سوالات چند گزینه\u200cای، گزینه\u200cها را با کاما جدا کنید', null=True, verbose_name='گزینه\u200cها')),
                ('options_fa', models.TextField(blank=True, help_text='برای سوالات چند گزینه\u200cای، گزینه\u200cهای فارسی را با کاما جدا کنید', null=True, verbose_name='گزینه\u200cهای فارسی')),
                ('is_required', models.BooleanField(default=True, verbose_name='اجباری')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='authapp.form', verbose_name='فرم')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='پاسخ متنی')),
                ('answer_number', models.FloatField(blank=True, null=True, verbose_name='پاسخ عددی')),
                ('answer_boolean', models.BooleanField(blank=True, null=True, verbose_name='پاسخ بله/خیر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='authapp.formresponse', verbose_name='پاسخ فرم')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='authapp.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ سوال',
                'verbose_name_plural': 'پاسخ\u200cهای سوالات',
                'unique_together': {('form_response', 'question')},
            },
        ),
    ]
