# Generated by Django 4.2.16 on 2025-11-01 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0007_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('APPROVED', 'تایید شده'), ('DENIED', 'رد شده'), ('CANCELLED', 'لغو شده')], default='PENDING', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('denied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denied_requests', to=settings.AUTH_USER_MODEL, verbose_name='رد کننده')),
                ('form_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_request', to='authapp.formresponse', verbose_name='پاسخ فرم')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests', to=settings.AUTH_USER_MODEL, verbose_name='بیمار')),
                ('psychological_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests', to='authapp.psychologicalissue', verbose_name='مسئله روانشناختی')),
            ],
            options={
                'verbose_name': 'درخواست جلسه',
                'verbose_name_plural': 'درخواست\u200cهای جلسه',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='authapp_ses_status_5827b3_idx')],
            },
        ),
    ]
