# Generated by Django 4.2.16 on 2025-11-03 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0008_sessionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='therapist_profiles/', verbose_name='تصویر پروفایل')),
                ('specializations', models.JSONField(blank=True, default=list, help_text='لیست تخصص\u200cها به صورت JSON array', verbose_name='تخصص\u200cها')),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال\u200cهای تجربه')),
                ('education', models.TextField(blank=True, null=True, verbose_name='تحصیلات')),
                ('certificates', models.JSONField(blank=True, default=list, help_text='لیست گواهینامه\u200cها به صورت JSON array', verbose_name='گواهینامه\u200cها')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='دلیل رد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_therapist_profiles', to=settings.AUTH_USER_MODEL, verbose_name='تأیید کننده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل تراپیست',
                'verbose_name_plural': 'پروفایل\u200cهای تراپیست\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_approved', '-created_at'], name='authapp_the_is_appr_bd98bb_idx')],
            },
        ),
    ]
