# Generated by Django 4.2.16 on 2025-11-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_therapistprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='patient_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید بیمار'),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='patient_choice',
            field=models.CharField(choices=[('PENDING', 'در انتظار انتخاب'), ('ACCEPTED', 'تایید شده توسط بیمار'), ('REJECTED', 'رد شده توسط بیمار')], default='PENDING', max_length=10, verbose_name='انتخاب بیمار'),
        ),
    ]
