# Generated by Django 4.2.16 on 2025-11-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_devicetoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceToken',
        ),
    ]
