# Generated by Django 4.2.16 on 2025-11-04 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0012_delete_devicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_sessions_as_patient', to=settings.AUTH_USER_MODEL, verbose_name='بیمار')),
                ('session_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_session', to='authapp.sessionrequest', verbose_name='درخواست جلسه')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_sessions_as_therapist', to=settings.AUTH_USER_MODEL, verbose_name='درمانگر')),
            ],
            options={
                'verbose_name': 'جلسه درمانی',
                'verbose_name_plural': 'جلسات درمانی',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('TEXT', 'متن'), ('VOICE', 'صدا'), ('IMAGE', 'تصویر')], default='TEXT', max_length=10, verbose_name='نوع پیام')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='ارسال کننده')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='authapp.therapysession', verbose_name='جلسه درمانی')),
            ],
            options={
                'verbose_name': 'پیام چت',
                'verbose_name_plural': 'پیام\u200cهای چت',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='therapysession',
            index=models.Index(fields=['patient', '-started_at'], name='authapp_the_patient_c1c4f5_idx'),
        ),
        migrations.AddIndex(
            model_name='therapysession',
            index=models.Index(fields=['therapist', '-started_at'], name='authapp_the_therapi_513041_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='authapp_cha_session_831a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='authapp_cha_sender__b6142c_idx'),
        ),
    ]
