# Generated by Django 4.2.16 on 2025-11-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_therapysession_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='voice_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_voices/', verbose_name='فایل صوتی'),
        ),
    ]
