# Generated by Django 4.2.16 on 2025-11-08 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0014_chatmessage_voice_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initiated', 'شروع شده'), ('ringing', 'در حال زنگ'), ('active', 'فعال'), ('ended', 'پایان یافته'), ('missed', 'از دست رفته'), ('rejected', 'رد شده')], default='initiated', max_length=20, verbose_name='وضعیت')),
                ('janus_session_id', models.BigIntegerField(blank=True, null=True, verbose_name='شناسه جلسه Janus')),
                ('janus_room_id', models.BigIntegerField(blank=True, null=True, verbose_name='شناسه اتاق Janus')),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='video_calls/', verbose_name='فایل ضبط شده')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('duration', models.IntegerField(default=0, verbose_name='مدت زمان (ثانیه)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_video_calls', to=settings.AUTH_USER_MODEL, verbose_name='تماس گیرنده')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_calls', to='authapp.therapysession', verbose_name='جلسه درمانی')),
            ],
            options={
                'verbose_name': 'تماس ویدیویی',
                'verbose_name_plural': 'تماس\u200cهای ویدیویی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoCallParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janus_handle_id', models.BigIntegerField(blank=True, null=True, verbose_name='شناسه handle Janus')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ورود')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_call_participations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('video_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='authapp.videocall', verbose_name='تماس ویدیویی')),
            ],
            options={
                'verbose_name': 'شرکت\u200cکننده تماس ویدیویی',
                'verbose_name_plural': 'شرکت\u200cکنندگان تماس\u200cهای ویدیویی',
                'indexes': [models.Index(fields=['video_call', 'user'], name='authapp_vid_video_c_844cc7_idx')],
                'unique_together': {('video_call', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='videocall',
            index=models.Index(fields=['session', '-created_at'], name='authapp_vid_session_511d58_idx'),
        ),
        migrations.AddIndex(
            model_name='videocall',
            index=models.Index(fields=['caller', '-created_at'], name='authapp_vid_caller__f317a2_idx'),
        ),
        migrations.AddIndex(
            model_name='videocall',
            index=models.Index(fields=['status', '-created_at'], name='authapp_vid_status_f2fe1c_idx'),
        ),
    ]
