# Generated by Django 4.2.16 on 2025-11-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_videocall_videocallparticipant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formresponse',
            unique_together=set(),
        ),
    ]
