# Generated by Django 4.2.16 on 2025-11-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_alter_formresponse_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videocallparticipant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='videocallparticipant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videocallparticipant',
            name='video_call',
        ),
        migrations.DeleteModel(
            name='VideoCall',
        ),
        migrations.DeleteModel(
            name='VideoCallParticipant',
        ),
    ]
