# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_alter_videocallparticipant_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='voice_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_voices/', verbose_name='فایل صوتی'),
        ),
    ]

