# Generated by Django 4.2.16 on 2025-12-02 14:08

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_alter_chatmessage_voice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='voice_file',
            field=models.FileField(blank=True, null=True, storage=core.storage_backends.LiaraMediaStorage(), upload_to='chat_voices/', verbose_name='فایل صوتی'),
        ),
    ]
