# Generated by Django 4.2.16 on 2025-12-02 14:24

import core.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0019_alter_chatmessage_voice_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('TEXT', 'متن'), ('IMAGE', 'تصویر'), ('VIDEO', 'ویدیو')], default='TEXT', max_length=10, verbose_name='نوع پست')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('image', models.ImageField(blank=True, null=True, storage=core.storage_backends.LiaraMediaStorage(), upload_to='posts/images/', verbose_name='تصویر')),
                ('video', models.FileField(blank=True, null=True, storage=core.storage_backends.LiaraMediaStorage(), upload_to='posts/videos/', verbose_name='ویدیو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='تراپیست')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('LIKE', '👍 لایک'), ('LOVE', '❤️ عشق'), ('SUPPORT', '🤝 حمایت'), ('THANKS', '🙏 تشکر'), ('INSIGHTFUL', '💡 بینش')], default='LIKE', max_length=20, verbose_name='نوع واکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='authapp.post', verbose_name='پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'واکنش پست',
                'verbose_name_plural': 'واکنش\u200cهای پست\u200cها',
                'indexes': [models.Index(fields=['post', 'user'], name='authapp_pos_post_id_886364_idx'), models.Index(fields=['post', 'reaction_type'], name='authapp_pos_post_id_825c4e_idx')],
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_active', '-created_at'], name='authapp_pos_is_acti_a51dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['therapist', '-created_at'], name='authapp_pos_therapi_0824fc_idx'),
        ),
    ]
