# Generated by Django 4.2.16 on 2025-12-04 16:28

import core.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0022_notification_devicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_support_staff', models.BooleanField(default=False, help_text='اگر True باشد، پیام از طرف تیم پشتیبانی است', verbose_name='کارمند پشتیبانی')),
                ('message_type', models.CharField(choices=[('TEXT', 'متن'), ('VOICE', 'صدا'), ('IMAGE', 'تصویر')], default='TEXT', max_length=10, verbose_name='نوع پیام')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('voice_file', models.FileField(blank=True, null=True, storage=core.storage_backends.LiaraMediaStorage(), upload_to='support_chat_voices/', verbose_name='فایل صوتی')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_support_messages', to=settings.AUTH_USER_MODEL, verbose_name='ارسال کننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیام پشتیبانی',
                'verbose_name_plural': 'پیام\u200cهای پشتیبانی',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='authapp_sup_user_id_f098f5_idx'), models.Index(fields=['sender', 'created_at'], name='authapp_sup_sender__f70248_idx'), models.Index(fields=['user', 'is_read'], name='authapp_sup_user_id_393ca4_idx')],
            },
        ),
    ]
