# Generated by Django 4.2.16 on 2025-12-12 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0025_fix_category_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0, verbose_name='موجودی')),
                ('reserved_balance', models.BigIntegerField(default=0, verbose_name='موجودی بلوکه شده')),
                ('currency', models.CharField(choices=[('IRR', 'ریال')], default='IRR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
            },
        ),
        migrations.AddField(
            model_name='form',
            name='session_price',
            field=models.BigIntegerField(default=0, verbose_name='هزینه هر جلسه (ریال)'),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('HELD', 'بلوکه شده'), ('PAID', 'واریز شده'), ('RELEASED', 'برگشت داده شده'), ('NOT_REQUIRED', 'نیاز به پرداخت ندارد')], default='PENDING', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='مبلغ جلسه'),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='price_currency',
            field=models.CharField(default='IRR', max_length=10, verbose_name='واحد پولی'),
        ),
        migrations.AlterField(
            model_name='sessionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'در انتظار پرداخت'), ('PENDING', 'در انتظار درمانگر'), ('APPROVED', 'تایید شده'), ('DENIED', 'رد شده'), ('CANCELLED', 'لغو شده')], default='PENDING_PAYMENT', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'واریز'), ('DEBIT', 'برداشت'), ('HOLD', 'بلوکه'), ('RELEASE', 'آزادسازی'), ('TRANSFER_IN', 'انتقال ورودی'), ('TRANSFER_OUT', 'انتقال خروجی'), ('ADJUSTMENT', 'اصلاح موجودی')], max_length=20)),
                ('amount', models.BigIntegerField(verbose_name='مبلغ')),
                ('currency', models.CharField(default='IRR', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
                ('balance_after', models.BigIntegerField(default=0, verbose_name='موجودی پس از تراکنش')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='authapp.sessionrequest', verbose_name='درخواست جلسه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='authapp.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='authapp_wal_user_id_3d2b4e_idx'), models.Index(fields=['session_request', '-created_at'], name='authapp_wal_session_2a768d_idx')],
            },
        ),
    ]
