# Generated by GapCode on 2026-06-05

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0027_psychologicalissue_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='profile_image',
            field=models.ImageField(
                blank=True,
                null=True,
                storage=core.storage_backends.LiaraMediaStorage(),
                upload_to='therapist_profiles/',
                verbose_name='تصویر پروفایل',
            ),
        ),
    ]
