# Generated by Django 4.2.16 on 2026-06-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0028_alter_therapistprofile_profile_image_storage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='psychologicalissue',
            new_name='authapp_psy_is_acti_0e82ac_idx',
            old_name='authapp_psy_is_acti_order_idx',
        ),
        migrations.RenameIndex(
            model_name='psychologicalissue',
            new_name='authapp_psy_categor_a1bf42_idx',
            old_name='authapp_psy_categor_order_idx',
        ),
    ]
