# Generated by Django 4.2.16 on 2026-06-11 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0030_therapistprofile_activity_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(default=0, verbose_name='قیمت پیشنهادی')),
                ('message', models.TextField(blank=True, null=True, verbose_name='پیام تراپیست')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار پیشنهاد'), ('ACCEPTED', 'تایید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('session_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='authapp.sessionrequest', verbose_name='درخواست جلسه')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_offers', to=settings.AUTH_USER_MODEL, verbose_name='درمانگر')),
            ],
            options={
                'verbose_name': 'پیشنهاد تراپیست',
                'verbose_name_plural': 'پیشنهادهای تراپیست',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_request', 'therapist'], name='authapp_the_session_909dac_idx')],
                'unique_together': {('session_request', 'therapist')},
            },
        ),
    ]
